version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: Europe/Paris
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        TZ: Europe/Paris
    image: laravel-php:8.4
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      TZ: Europe/Paris
    volumes:
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
      - storage:/var/www/html/storage
      - composer-cache:/tmp/composer
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        TZ: Europe/Paris
    container_name: apache
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
    depends_on:
      php-fpm:
        condition: service_healthy

  horizon:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PUID: 1000
        PGID: 1000
        TZ: Europe/Paris
    image: laravel-php:8.4
    container_name: horizon
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      REDIS_HOST: redis
      TZ: Europe/Paris
    volumes:
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
      - storage:/var/www/html/storage
      - composer-cache:/tmp/composer
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["php", "artisan", "horizon"]

volumes:
  mysql-data:
  redis-data:
  vendor:
  storage:
  composer-cache:
