version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - redis

  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php-fpm

  horizon:
    build:
      context: .
      dockerfile: docker/horizon/Dockerfile
    container_name: horizon
    volumes:
      - ./src:/var/www/html
    depends_on:
      - redis
      - mysql
    command: bash -lc "composer install && php artisan horizon"

volumes:
  mysql-data:
  redis-data:
